// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajfpcvhmloagkejzshsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZnBjdmhtbG9hZ2tlanpzaHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDE2NDYsImV4cCI6MjA3MzQ3NzY0Nn0._Gei627fvGeZ7vq_jczRWQYmLXmto7XAvit2_FxwHJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});